CREATE TABLE buildings (
    code VARCHAR(20) PRIMARY KEY,
    name VARCHAR(150) NOT NULL,
    address VARCHAR(255),
    number_of_floors INTEGER,
    description TEXT,
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',

    CONSTRAINT chk_building_floors
        CHECK (
            number_of_floors IS NULL
            OR number_of_floors > 0
        ),

    CONSTRAINT chk_building_status
        CHECK (status IN ('ACTIVE', 'INACTIVE'))
);

CREATE TABLE rooms (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_number VARCHAR(30) NOT NULL,
    building_code VARCHAR(20) NOT NULL,
    monthly_rent NUMERIC(12, 2) NOT NULL DEFAULT 0,
    maximum_capacity INTEGER NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',

    CONSTRAINT uk_room_building_number
        UNIQUE (room_number, building_code),

    CONSTRAINT fk_room_building
        FOREIGN KEY (building_code)
        REFERENCES buildings(code)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT chk_room_rent
        CHECK (monthly_rent >= 0),

    CONSTRAINT chk_room_capacity
        CHECK (maximum_capacity > 0),

    CONSTRAINT chk_room_status
        CHECK (status IN ('ACTIVE', 'INACTIVE'))
);

CREATE TABLE students (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name VARCHAR(150) NOT NULL,
    gender VARCHAR(20),
    citizen_id VARCHAR(30) UNIQUE,
    phone_number VARCHAR(30),
    date_of_birth DATE,
    address TEXT,
    student_code VARCHAR(30) NOT NULL UNIQUE,
    class_name VARCHAR(100),
    major VARCHAR(150),
    hometown VARCHAR(150),
    room_id BIGINT,

    CONSTRAINT fk_student_room
        FOREIGN KEY (room_id)
        REFERENCES rooms(id)
        ON UPDATE CASCADE
        ON DELETE SET NULL,

    CONSTRAINT chk_student_gender
        CHECK (
            gender IS NULL
            OR gender IN ('MALE', 'FEMALE', 'OTHER')
        )
);

CREATE TABLE management_staff (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name VARCHAR(150) NOT NULL,
    gender VARCHAR(20),
    citizen_id VARCHAR(30) UNIQUE,
    phone_number VARCHAR(30) UNIQUE,
    date_of_birth DATE,
    address TEXT,
    employee_code VARCHAR(30) NOT NULL UNIQUE,
    assigned_building_code VARCHAR(20),

    CONSTRAINT fk_staff_building
        FOREIGN KEY (assigned_building_code)
        REFERENCES buildings(code)
        ON UPDATE CASCADE
        ON DELETE SET NULL,

    CONSTRAINT chk_staff_gender
        CHECK (
            gender IS NULL
            OR gender IN ('MALE', 'FEMALE', 'OTHER')
        )
);