<script setup lang="ts">
import { ref, computed, onMounted } from 'vue';
import { useStaffStore } from '../stores/staffStore';
import { useToast } from 'vue-toastification';
import { Plus, Search } from '@lucide/vue';
import { getErrorMessage } from '../services/api';
import type { NewStaff, Staff } from '../types/staff';

const staffStore = useStaffStore();
const toast = useToast();
const staffList = computed(() => staffStore.staffList);

onMounted(async () => {
  try {
    await staffStore.fetchStaff();
  } catch (error) {
    toast.error(getErrorMessage(error));
  }
});

const searchQuery = ref('');
const selectedBuilding = ref('All');
const isAddEditModalOpen = ref(false);

const editingStaffId = ref<number | null>(null);
const buildingsList = ['Building A', 'Building B', 'Building C'];

const newStaff = ref<NewStaff>({
  employeeCode: '',
  fullName: '',
  gender: 'MALE',
  dateOfBirth: '',
  citizenId: '',
  phoneNumber: '',
  address: '',
  assignedBuildingCode: '',
});

const filteredStaff = computed(() => {
  return staffList.value.filter((s) => {
    const matchesSearch =
      s.fullName.toLowerCase().includes(searchQuery.value.toLowerCase()) ||
      s.employeeCode.toLowerCase().includes(searchQuery.value.toLowerCase()) ||
      s.phoneNumber.includes(searchQuery.value);

    const matchesBuilding =
      selectedBuilding.value === 'All' || s.assignedBuildingName === selectedBuilding.value;

    return matchesSearch && matchesBuilding;
  });
});

const openAddModal = () => {
  editingStaffId.value = null;
  isAddEditModalOpen.value = true;
};

const openEditModal = (staff: Staff) => {
  editingStaffId.value = staff.id;
  newStaff.value = {
    employeeCode: staff.employeeCode,
    fullName: staff.fullName,
    gender: staff.gender,
    dateOfBirth: staff.dateOfBirth,
    citizenId: staff.citizenId,
    phoneNumber: staff.phoneNumber,
    address: staff.address,
    assignedBuildingCode: staff.assignedBuildingCode,
  };
  isAddEditModalOpen.value = true;
};

const handleSaveStaff = async () => {
  if (!newStaff.value.name) {
    alert('Vui lòng điền tên nhân viên!');
    return;
  }

  if (editingStaffId.value) {
    await staffStore.updateStaff(editingStaffId.value, { ...newStaff.value });
  } else {
    const autoGeneratedId = 'ST' + Math.floor(1000 + Math.random() * 9000);
    await staffStore.addStaff({
      ...newStaff.value,
      staffId: autoGeneratedId,
    });
  }
  isAddEditModalOpen.value = false;
};

const handleDeleteStaff = async (id: number, name: string) => {
  if (confirm(`Bạn có chắc chắn muốn xóa nhân viên ${name}?`)) {
    await staffStore.deleteStaff(id);
  }
};
</script>

<template>
  <div class="p-6 max-w-7xl mx-auto space-y-6">
    <!-- Header -->
    <div class="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4">
      <div>
        <h1 class="text-2xl font-bold text-gray-900">Staff Management</h1>
        <p class="text-sm text-gray-500 mt-1">Manage dormitory managers and building assignments</p>
      </div>
      <button
        @click="openAddModal"
        class="inline-flex items-center justify-center px-4 py-2.5 gap-2 bg-blue-600 hover:bg-blue-700 text-white text-sm font-medium rounded-lg transition-colors shadow-sm cursor-pointer"
      >
        <Plus :size="20" />
        <span>Add staff</span>
      </button>
    </div>

    <!-- Filters -->
    <div
      class="bg-white p-4 rounded-xl shadow-sm border border-gray-100 flex flex-col sm:flex-row gap-4"
    >
      <div class="flex-1 relative">
        <span class="absolute inset-y-0 left-3 flex items-center text-gray-400">
          <Search :size="20" />
        </span>
        <input
          v-model="searchQuery"
          type="text"
          placeholder="Search staff by name or phone..."
          class="w-full pl-9 pr-4 py-2 bg-gray-50 border border-gray-200 rounded-lg text-sm focus:outline-none focus:border-blue-500 focus:bg-white transition-colors"
        />
      </div>
      <div class="w-full sm:w-64 flex items-center space-x-2">
        <span class="text-sm text-gray-500 whitespace-nowrap">Assigned Building:</span>
        <select
          v-model="selectedBuilding"
          class="w-full px-3 py-2 bg-gray-50 border border-gray-200 rounded-lg text-sm focus:outline-none focus:border-blue-500 focus:bg-white transition-colors"
        >
          <option value="All">All</option>
          <option v-for="b in buildingsList" :key="b" :value="b">
            {{ b }}
          </option>
          <option value="None">None (Unassigned)</option>
        </select>
      </div>
    </div>

    <!-- Data Table -->
    <div class="bg-white rounded-xl shadow-sm border border-gray-100 overflow-hidden">
      <div class="overflow-x-auto">
        <table class="w-full text-left border-collapse">
          <thead>
            <tr
              class="bg-gray-50 border-b border-gray-100 text-xs font-semibold text-gray-500 uppercase tracking-wider"
            >
              <th class="px-6 py-4">Name</th>
              <th class="px-6 py-4">Code</th>
              <th class="px-6 py-4">Phone Number</th>
              <th class="px-6 py-4">Assigned Building</th>
              <th class="px-6 py-4 text-right">Actions</th>
            </tr>
          </thead>
          <tbody class="divide-y divide-gray-100 text-sm text-gray-700">
            <tr
              v-for="s in filteredStaff"
              :key="s.id"
              class="hover:bg-gray-50/70 transition-colors"
            >
              <td class="px-6 py-4 font-semibold text-gray-900">
                {{ s.fullName }}
              </td>
              <td class="px-6 py-4 text-gray-500">{{ s.employeeCode }}</td>
              <td class="px-6 py-4 text-gray-500">{{ s.phoneNumber }}</td>
              <td class="px-6 py-4">
                <span
                  :class="
                    s.assignedBuildingName === 'None'
                      ? 'text-gray-400 italic'
                      : 'font-medium text-gray-950'
                  "
                >
                  {{ s.assignedBuildingName }}
                </span>
              </td>
              <td class="px-6 py-4 text-right space-x-2 text-sm font-medium">
                <button @click="openEditModal(s)" class="text-blue-600 hover:text-blue-900">
                  Edit
                </button>
                <button
                  @click="handleDeleteStaff(s.id!, s.fullName)"
                  class="text-rose-600 hover:text-rose-900 ml-2"
                >
                  Delete
                </button>
              </td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>

    <!-- MODAL -->
    <div
      v-if="isAddEditModalOpen"
      class="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/40 backdrop-blur-sm"
    >
      <div
        class="bg-white w-full max-w-md max-h-[calc(100vh-2rem)] rounded-xl shadow-xl border border-gray-100 overflow-hidden flex flex-col"
      >
        <div class="shrink-0 px-6 py-4 border-b border-gray-100 flex items-center justify-between">
          <h3 class="text-base font-bold text-gray-900">
            {{ editingStaffId ? 'Edit Staff Member' : 'Add Staff Member' }}
          </h3>
          <button @click="isAddEditModalOpen = false" class="text-gray-400 hover:text-gray-600">
            ✕
          </button>
        </div>
        <div class="p-6 space-y-4 flex-1 min-h-0 overflow-y-auto">
          <div>
            <label class="block text-xs font-semibold text-gray-600 uppercase mb-1"
              >Employee Code *</label
            >
            <input
              v-model="newStaff.employeeCode"
              type="text"
              class="w-full px-3 py-2 border border-gray-200 rounded-lg text-sm focus:outline-none focus:border-blue-500"
            />
          </div>
          <div>
            <label class="block text-xs font-semibold text-gray-600 uppercase mb-1"
              >Full Name *</label
            >
            <input
              v-model="newStaff.fullName"
              type="text"
              class="w-full px-3 py-2 border border-gray-200 rounded-lg text-sm focus:outline-none focus:border-blue-500"
            />
          </div>
          <div>
            <label class="block text-xs font-semibold text-gray-600 uppercase mb-1"
              >Date of birth *</label
            >
            <input
              v-model="newStaff.dateOfBirth"
              type="text"
              class="w-full px-3 py-2 border border-gray-200 rounded-lg text-sm focus:outline-none focus:border-blue-500"
            />
          </div>
          <div>
            <label class="block text-xs font-semibold text-gray-600 uppercase mb-1"
              >Phone Number *</label
            >
            <input
              v-model="newStaff.phoneNumber"
              type="text"
              class="w-full px-3 py-2 border border-gray-200 rounded-lg text-sm focus:outline-none focus:border-blue-500"
            />
          </div>
          <div>
            <label class="block text-xs font-semibold text-gray-600 uppercase mb-1"
              >Assign to Building</label
            >
            <select
              v-model="newStaff.assignedBuildingCode"
              class="w-full px-3 py-2 border border-gray-200 rounded-lg text-sm bg-white focus:outline-none focus:border-blue-500"
            >
              <option value="None">-- Leave Unassigned --</option>
              <option v-for="b in buildingsList" :key="b" :value="b">
                {{ b }}
              </option>
            </select>
          </div>
          <div>
            <label class="block text-xs font-semibold text-gray-600 uppercase mb-1">Status</label>
            <select
              v-model="newStaff.status"
              class="w-full px-3 py-2 border border-gray-200 rounded-lg text-sm bg-white focus:outline-none focus:border-blue-500"
            >
              <option value="Active">Active</option>
              <option value="Inactive">Inactive</option>
            </select>
          </div>
        </div>
        <div
          class="shrink-0 px-6 py-4 bg-gray-50 border-t border-gray-100 flex items-center justify-end space-x-3"
        >
          <button
            @click="isAddEditModalOpen = false"
            class="px-4 py-2 text-sm font-medium text-gray-600 hover:text-gray-800 bg-white border border-gray-200 rounded-lg hover:bg-gray-50 transition-colors"
          >
            Cancel
          </button>
          <button
            @click="handleSaveStaff"
            class="px-4 py-2 text-sm font-medium text-white bg-blue-600 hover:bg-blue-700 rounded-lg transition-colors shadow-sm"
          >
            Save staff
          </button>
        </div>
      </div>
    </div>
  </div>
</template>
